### ISSUE TITLE
build: not generating variable fonts

### ISSUE THREAD

**Issue by wayne-shih** [WCYS-Co/Hauora-Sans#41]
font make currently not generating variable fonts 

this is due to rollback of reqs https://github.com/WCYS-Co/Hauora-Sans/commit/07059c3111c0fa61fb3aaf6023619d03b68c587c as it was causing issues... see https://github.com/WCYS-Co/Hauora-Sans/runs/6848350794?check_suite_focus=true

```
2022-06-12T07:11:50.7310219Z ERROR:cu2qu.ufo:Glyphs named 'dieresistonos' have different number of segments
2022-06-12T07:11:50.7353808Z ERROR:cu2qu.ufo:Glyphs named 'divide' have different number of segments
2022-06-12T07:11:50.8269010Z ERROR:cu2qu.ufo:Glyphs named 'exclam' have different number of segments
2022-06-12T07:11:50.8698533Z Traceback (most recent call last):
2022-06-12T07:11:50.8713815Z   File "/home/runner/work/Hauora-Sans/Hauora-Sans/venv/lib/python3.8/site-packages/fontmake/font_project.py", line 1003, in run_from_designspace
2022-06-12T07:11:50.8715128Z     self._run_from_designspace_interpolatable(
2022-06-12T07:11:50.8716106Z   File "/home/runner/work/Hauora-Sans/Hauora-Sans/venv/lib/python3.8/site-packages/fontmake/font_project.py", line 1086, in _run_from_designspace_interpolatable
2022-06-12T07:11:50.8716568Z     self.build_variable_font(
2022-06-12T07:11:50.8717431Z   File "/home/runner/work/Hauora-Sans/Hauora-Sans/venv/lib/python3.8/site-packages/fontmake/font_project.py", line 342, in build_variable_font
2022-06-12T07:11:50.8717918Z     font = ufo2ft.compileVariableTTF(
2022-06-12T07:11:50.8718584Z   File "/home/runner/work/Hauora-Sans/Hauora-Sans/venv/lib/python3.8/site-packages/ufo2ft/__init__.py", line 547, in compileVariableTTF
2022-06-12T07:11:50.8719055Z     ttfDesignSpace = compileInterpolatableTTFsFromDS(
2022-06-12T07:11:50.8719788Z   File "/home/runner/work/Hauora-Sans/Hauora-Sans/venv/lib/python3.8/site-packages/ufo2ft/__init__.py", line 376, in compileInterpolatableTTFsFromDS
2022-06-12T07:11:50.8720274Z     for source, ttf in zip(result.sources, ttfs):
2022-06-12T07:11:50.8720937Z   File "/home/runner/work/Hauora-Sans/Hauora-Sans/venv/lib/python3.8/site-packages/ufo2ft/__init__.py", line 288, in compileInterpolatableTTFs
2022-06-12T07:11:50.8721376Z     glyphSets = call_preprocessor(ufos, **kwargs)
2022-06-12T07:11:50.8722008Z   File "/home/runner/work/Hauora-Sans/Hauora-Sans/venv/lib/python3.8/site-packages/ufo2ft/__init__.py", line 63, in call_preprocessor
2022-06-12T07:11:50.8722462Z     return preProcessor.process()
2022-06-12T07:11:50.8723081Z   File "/home/runner/work/Hauora-Sans/Hauora-Sans/venv/lib/python3.8/site-packages/ufo2ft/preProcessor.py", line 316, in process
2022-06-12T07:11:50.8723479Z     fonts_to_quadratic(
2022-06-12T07:11:50.8724070Z   File "/home/runner/work/Hauora-Sans/Hauora-Sans/venv/lib/python3.8/site-packages/cu2qu/ufo.py", line 295, in fonts_to_quadratic
2022-06-12T07:11:50.8724544Z     raise IncompatibleFontsError(glyph_errors)
2022-06-12T07:11:50.8725132Z cu2qu.errors.IncompatibleFontsError: fonts contains incompatible glyphs: 'dieresistonos', 'divide', 'exclam'
2022-06-12T07:11:50.8725433Z 
2022-06-12T07:11:50.8725615Z The above exception was the direct cause of the following exception:
2022-06-12T07:11:50.8725834Z 
2022-06-12T07:11:50.8725939Z Traceback (most recent call last):
2022-06-12T07:11:50.8726479Z   File "/home/runner/work/Hauora-Sans/Hauora-Sans/venv/bin/gftools-builder.py", line 83, in <module>
2022-06-12T07:11:50.8726847Z     builder.build()
2022-06-12T07:11:50.8727422Z   File "/home/runner/work/Hauora-Sans/Hauora-Sans/venv/lib/python3.8/site-packages/gftools/builder/__init__.py", line 192, in build
2022-06-12T07:11:50.8727804Z     self.build_variable()
2022-06-12T07:11:50.8728410Z   File "/home/runner/work/Hauora-Sans/Hauora-Sans/venv/lib/python3.8/site-packages/gftools/builder/__init__.py", line 294, in build_variable
2022-06-12T07:11:50.8728858Z     output_files = self.run_fontmake(source, args)
2022-06-12T07:11:50.8729491Z   File "/home/runner/work/Hauora-Sans/Hauora-Sans/venv/lib/python3.8/site-packages/gftools/builder/__init__.py", line 334, in run_fontmake
2022-06-12T07:11:50.8729930Z     FontProject().run_from_glyphs(source, **args)
2022-06-12T07:11:50.8730577Z   File "/home/runner/work/Hauora-Sans/Hauora-Sans/venv/lib/python3.8/site-packages/fontmake/font_project.py", line 741, in run_from_glyphs
2022-06-12T07:11:50.8731037Z     self.run_from_designspace(designspace_path, **kwargs)
2022-06-12T07:11:50.8732090Z   File "/home/runner/work/Hauora-Sans/Hauora-Sans/venv/lib/python3.8/site-packages/fontmake/font_project.py", line 1017, in run_from_designspace
2022-06-12T07:11:50.8732514Z     raise FontmakeError(
2022-06-12T07:11:50.8733214Z fontmake.errors.FontmakeError: In 'Hauora.glyphs' -> 'master_ufo/Hauora.designspace': Generating fonts from Designspace failed: fonts contains incompatible glyphs: 'dieresistonos', 'divide', 'exclam'
2022-06-12T07:11:51.0838078Z make: *** [Makefile:22: build.stamp] Error 1
2022-06-12T07:11:51.0854609Z ##[error]Process completed with exit code 2.
```

**Comment by wayne-shih** [comment]
fontmake also doesn't generate woff 
need to add another build to generate that...
